name: CI - API Gateway

on:
  push:
    paths:
      - 'api-gateway/**'
      - '.github/workflows/CI-API.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-gateway
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: api-gateway/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./api-gateway
          threshold: 50
          test-script: npx cross-env NODE_OPTIONS=--experimental-vm-modules jest --coverage --coverageReporters="json-summary" --coverageReporters="text" --coverageReporters="clover" --detectOpenHandles

      - name: Run Tests (push)
        if: github.event_name == 'push'
        run: npx cross-env NODE_OPTIONS=--experimental-vm-modules jest --detectOpenHandles
