name: CI - Submission Service

on:
  push:
    paths:
      - 'submission-service/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./submission-service
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: submission-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./submission-service
          threshold: 50

      - name: Lint
        run: npm run lint
