name: CI - Submission Service

on:
  push:
    paths:
      - 'submission-service/**'
      - '.github/workflows/CI-submission-service.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./submission-service
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: submission-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./submission-service
          threshold: 50

      - name: Run Tests (push)
        if: github.event_name == 'push'
        run: npx jest --detectOpenHandles
